services:
  - type: web
    name: lams
    runtime: docker
    plan: free
    repo: https://github.com/coffeescripttech-maker/LAMS
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: ASSET_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: LOG_CHANNEL
        value: errorlog
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_SAME_SITE
        value: lax
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync

databases:
  - name: lams-db
    databaseName: lams
    user: lams
    plan: free
