services:
  - type: web
    name: lams-fingerprint-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 7000
      - key: SIMILARITY_THRESHOLD
        value: 0.75
